 
import { NgModule } from '@angular/core';
import {
      MatButtonModule,      
      MatMenuModule,      
      MatToolbarModule,      
      MatIconModule,      
      MatCardModule,      
      MatFormFieldModule,      
      MatInputModule,      
      MatDatepickerModule,      
      MatDatepicker,      
      MatNativeDateModule,      
      MatRadioModule,      
      MatSelectModule,      
      MatOptionModule,      
      MatSlideToggleModule,
      MatCheckboxModule, MatGridList, MatGridTile, MatGridListModule,MatExpansionModule,
      MatSliderModule,
      MatAutocompleteModule,
      MatProgressSpinnerModule,
      MatSnackBarModule,
      MatDialogModule,
      MatRadioButton
} from '@angular/material'; 

@NgModule({
      imports: [MatButtonModule, 
            MatAutocompleteModule,     
            MatMenuModule,      
            MatToolbarModule,      
            MatIconModule,      
            MatCardModule,      
            MatFormFieldModule,      
            MatInputModule,      
            MatDatepickerModule,     
            MatNativeDateModule,      
            MatRadioModule,      
            MatSelectModule,      
            MatOptionModule,      
            MatSlideToggleModule,MatExpansionModule,
            MatCheckboxModule, MatGridListModule,
            MatSliderModule, MatProgressSpinnerModule,
            MatSnackBarModule, MatDialogModule],
      exports: [MatButtonModule,
            MatAutocompleteModule,      
            MatMenuModule,      
            MatToolbarModule,      
            MatIconModule,      
            MatCardModule,      
            MatFormFieldModule,      
            MatInputModule,      
            MatDatepickerModule,    
            MatNativeDateModule,      
            MatRadioModule,      
            MatSelectModule,      
            MatOptionModule,      
            MatSlideToggleModule,MatExpansionModule,
            MatCheckboxModule, MatGridListModule,
            MatSliderModule, MatProgressSpinnerModule,
            MatSnackBarModule, MatDialogModule],
      declarations: []
})
export class MaterialdesignModule { }
